### ISSUE TITLE
Add support for SolarEdge inverter

### ISSUE THREAD

**Issue by CleverOctopi** [deg0nz/MMM-Fronius2#4]
I would like to be able to use this to monitor my solar install. It's going to be using a SolarEdge SE6000H-US Inverter w/ SetApp.

**Comment by deg0nz** [comment]
This would be possible. After a quick search I found that this device should support SunSpec (MODBUS via TCP), which I already use for the Fronius converter.

If you are not willing or able to contribute and build this yourself, I cannot guarantee that this will be implemented anytime soon. Maybe I'll find time to build this in the winter.

Link to the docs: https://www.solaredge.com/sites/default/files/sunspec-implementation-technical-note.pdf

**Comment by CleverOctopi** [comment]
I am willing and hopefully able. I'm currently waiting on my system to be
installed so I can start attending access

**Comment by deg0nz** [comment]
@CleverOctopi Just a quick hint: Did you notice that there are already 3 modules for SolarEdge in the MM 3rd Party modules list? https://github.com/MichMich/MagicMirror/wiki/3rd-Party-Modules 

Maybe one of them already fits your requirements

**Comment by CleverOctopi** [comment]
I did not actually see those. My mistake.
