### ISSUE TITLE
Fronius Gen24 connect over Fritzbox

### ISSUE THREAD

**Issue by jojo2203** [deg0nz/MMM-Fronius2#5]
I have problems calling up and presenting the data from my Fronius Gen24 on my Magicmirror. Which IP address I have to use. The address with which he is registered in the Fritzbox. I need further information, parameters etc. according to the IP. Actually, I would also have to specify registration email and a passport? But I don't find it in your examples?

Thanks.

**Comment by deg0nz** [comment]
@jojo2203 Sorry for the delay. Is this still relevant?

**Comment by deg0nz** [comment]
Closing because of missing feedback
