### ISSUE TITLE
Label displays

### ISSUE THREAD

**Issue by sepulvar** [deg0nz/MMM-Fronius2#7]
Great improvement from previous version (MMM-fronius), in particular breaking down the units which I had done manually in previous one. Just one comment for consideration in future releases.. "Now" is ok to display at W or KW level... the rest.. Today, Year, Total should be Wh (Watt hour) units.. either KWh, MWh or GWh units.

Thanks

**Comment by deg0nz** [comment]
Just FYI: This module is not related to MMM-Fronius. I looked into the code there and decided to implement it myself.

Regarding the units: I will take care of that for the next release. I plan to work on it in January 2024. So please be a little more patient :)

**Comment by deg0nz** [comment]
Should be fixed with https://github.com/deg0nz/MMM-Fronius2/commit/a73bafc99cd4ac5ee4f29daa42af1b6c901c7f19
