### ISSUE TITLE
Get no Data from inverter

### ISSUE THREAD

**Issue by Dawil1987** [deg0nz/MMM-Fronius2#8]
Hi,

i try to implement the Module to my MagicMirror.
Unfortunally i get no Values from the inverter or the hole system.
I changed the IP Address as described.
The Problem, the Program will not start.
If i start now the Program i get an Error "[ERROR] (node:1921) UnhandledPromiseRejectionWarning: Error: Cannot find module 'node-fetch'"
If i deactivate the "const fetch = require("node-fetch");" with "//" in the FroniusFetcher.js.
After this another erro occur "[ERROR] (node:2037) UnhandledPromiseRejectionWarning: Error: Cannot find module 'node-abort-controller'"
I deactivate the "cconst AbortController = require("node-abort-controller").AbortController;" with "//" in the FroniusFetcher.js.
After this the Programm starts without an issue. But i get no Values or Data.

Could please anybody help what i have to do?
Unfortunately I do not know myself with the programming and understand the codes unfortunately also only very little

I have the MagicMirror Version 2.25.0 with Raspberry Pi OS (legacy) Full

Thanks in advance.

**Comment by deg0nz** [comment]
Did you execute `npm install` inside the module directory?

And if yes, could you please post your NodeJS version? (output of `node --version`)

**Comment by Dawil1987** [comment]
Hi Beh,Thanks a lot for your reply.Ist was the missing npm install command.Thanks a lot for your help.Much appreciated.Best regards.Mit freundlichen GrüßenDaniel WillnerAm 01.11.2023 um 21:21 schrieb Beh ***@***.***>:﻿
Did you execute npm install inside the module directory?
And if yes, could you please post your NodeJS version? (output of node --version)

**Comment by Dawil1987** [comment]
Thanks for the reply.
It was the missing npm install command.
Thanks for your help.
Much appreciated.
